### ISSUE TITLE
Exception while invoking method 'Accounts.createUnverifiedUser'

### ISSUE THREAD

**Issue by raphaelarias** [ejfrancis/Meteor-Vue-Modular-App-Starter#35]
`TypeError: Cannot read property 'emails' of undefined
 Object.Accounts.emailTemplates.enrollAccount.from (src/imports/modules/accounts/server/email/enroll-account-email.js:5:57)`

**Comment by ejfrancis** [comment]
hey @raphaelarias 

It looks like your app isn't finding the config file's values [on this line](https://github.com/ejfrancis/Meteor-Vue-Enterprise-Starter/blob/master/src/imports/modules/accounts/server/email/enroll-account-email.js#L5). Did you run the app by running `meteor` or by running `meteor npm run start`? You'll see in the [package.json](https://github.com/ejfrancis/Meteor-Vue-Enterprise-Starter/blob/master/package.json#L5) that `meteor npm run start` should pass in the config file via the `--settings` flag

**Comment by raphaelarias** [comment]
Oh, my mistake. I was looking forward to see how it looked like that I forgot this part.

Thanks and sorry. :)

**Comment by ejfrancis** [comment]
no problem! if you're trying to create a new user, you'll have to watch the terminal because in local development instead of sending an email it will just dump the email's contents into your terminal. you'll see the link and the token generated in that email which you can use to finish setting up your account

**Comment by raphaelarias** [comment]
Yep, no worries. Great work!
